services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports: [ "${PORT}:3000" ]
    env_file: .env
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PORT=3000
      - NODE_ENV=production
    volumes: [ "./kv_store.sqlite:/home/bun/app/kv_store.sqlite" ]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    restart: unless-stopped
  
  sql-studio:
    image: "frectonz/sql-studio"
    ports:
      - "3030:3030"
    volumes:
      - "./kv_store.sqlite:/data/kv_store.sqlite"
    command: ["/bin/sql-studio", "--no-browser", "--no-shutdown", "--address=0.0.0.0:3030", "sqlite", "/data/kv_store.sqlite"]